# Generated by Django 2.2.5 on 2019-11-13 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='businesses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='businesses.Business'),
        ),
    ]
