# Generated by Django 2.2.5 on 2019-11-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191127_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='businesses',
            field=models.ManyToManyField(blank=True, related_name='posts', to='businesses.Business'),
        ),
    ]
